"""empty message

Revision ID: b0ccaa7b6910
Revises: 
Create Date: 2021-12-24 14:53:29.311827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ccaa7b6910'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_link_id', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=24), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_link_id', sa.String(length=12), nullable=False),
    sa.Column('reddit_link', sa.String(length=128), nullable=False),
    sa.Column('reddit_title', sa.String(length=256), nullable=False),
    sa.Column('reddit_created_utc', sa.Integer(), nullable=False),
    sa.Column('reddit_subreddit', sa.String(length=24), nullable=False),
    sa.Column('imgur_iframe', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_link', sa.String(length=512), nullable=True),
    sa.Column('w2c_link', sa.String(length=512), nullable=True),
    sa.Column('gl_counter', sa.Integer(), nullable=True),
    sa.Column('rl_counter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_link_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeds')
    op.drop_table('errors')
    # ### end Alembic commands ###
